extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern const Trajectory bob_area_1_spline_NurbsCurve[];
extern Lights1 bob_dl_wall_lights;
extern Lights1 bob_dl_grass_lights;
extern u8 bob_dl_wf_textures_04800_rgba16_ci8[];
extern u8 bob_dl_wf_textures_04800_rgba16_pal_rgba16[];
extern u8 bob_dl_wf_textures_05800_rgba16_ci8[];
extern u8 bob_dl_wf_textures_05800_rgba16_pal_rgba16[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_0[64];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_1[64];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_1[];
extern Gfx mat_bob_dl_wall[];
extern Gfx mat_revert_bob_dl_wall[];
extern Gfx mat_bob_dl_grass[];
extern Gfx mat_revert_bob_dl_grass[];
extern Gfx bob_dl_Cube_mesh_layer_1[];
